### ISSUE TITLE
Nice work on the IDE

### ISSUE THREAD

**Issue by MySpaceEmoCat** [yikuansun/yikuansun#2]
Nice work on the IDE, sorry for not replying, I have been moving this month. Feel free to ping me if you need any further help. And thanks for adding me to the contrib list.

**Comment by yikuansun** [comment]
Thanks for contributing!!

**Comment by yikuansun** [comment]
I'm gonna be dropping a new release later this month with a more compact menu like you suggested (but also maintain the ability to return to the Main Menu). After that, I'll work on making a better file selector.

**Comment by yikuansun** [comment]
Latest release has it all!

**Comment by MySpaceEmoCat** [comment]
Awesome work! Looks really clean!
